<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="TestRunner" Id="{31f4ab78-3c98-459b-a21c-1adba1822291}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM TestRunner
VAR
	fbTestOTelMetricCore : FB_Test_OTelMetricCore;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.Run();
fbTestOTelMetricCore();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>