<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="LogTester" Id="{4d1f005e-af51-4c56-9181-252b1151b26e}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'}
{attribute 'no_explicit_call' := 'This FB is a CLASS and must be accessed using methods or properties'}
{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK PUBLIC LogTester
VAR
	logger : Nepionic_Log.DefaultLogger('LogTesterFunctionBlock');
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="YeahBoi" Id="{136f0e93-85c9-4de4-b5f3-8cf573aef9fd}">
      <Declaration><![CDATA[METHOD PUBLIC YeahBoi]]></Declaration>
      <Implementation>
        <ST><![CDATA[logger.Info('Yeah boi!');
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>